### PR TITLE
Correct typos and other errors

### PR DESCRIPTION
**Pull request by paulinevos**
I was asked to review a document on this repo and noticed some errors, so I decided to open this PR for it.

### CODE REVIEW

**Comment by paulinevos** [comment]
This repo doesn't seem to be active anymore, so I guess I'll close this.

**Comment by hcorona** [comment]
Hi @paulinevos I am really sorry, I never read the notifications for this  merge request until now that you closed!

**Review by hcorona — COMMENTED** [review]
👍

**Comment by hcorona** [comment]
I am going to merge this, thanks so much for the contributions!

**Comment by paulinevos** [comment]
@hcorona Oh no worries, thanks for merging! I figured it was just not active anymore.

**Pull request merged**
